name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest

      - name: Linter avec flake8
        run: |
          echo "Vérification avec flake8..."
          flake8 src/ tests/

      - name: Linter avec black
        run: |
          echo "Vérification avec black..."
          black --check src/ tests/

      - name: Linter avec isort
        run: |
          echo "Vérification avec isort..."
          isort --check-only src/ tests/

      - name: Lancer les tests unitaires
        run: |
          echo "Lancement des tests unitaires..."
          pytest --maxfail=1 --disable-warnings -q
